### ISSUE TITLE
Query question

### ISSUE THREAD

**Issue by tielur** [Planeshifter/node-sparqling-star#2]
How would I go about creating this query using node-sparqling-star?

```
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbpedia: <http://dbpedia.org/resource/>
SELECT ?currentteam WHERE { dbpedia:Philip_Rivers dbp:currentteam ?currentteam}
```

[SPARQL results](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=PREFIX+dbo%3A+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0D%0APREFIX+dbpedia%3A+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%0D%0ASELECT+%3FCurrentTeam+WHERE+%7B+dbpedia%3APhilip_Rivers+dbp%3Acurrentteam+%3FCurrentTeam%7D&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on)

**Comment by tielur** [comment]
I've tried: 

``` js
var sparqls = require( 'sparqling-star' );
var myquery = new sparqls.Query();
var search = {
    'dbpedia': 'Philip_Rivers',
};
myquery.selection( 'rdp:currentteam' );
myquery.registerVariable( 'search', search );
console.log(myquery.sparqlQuery);
```

but that produces:

```
SELECT ?rdp:currentteam 
WHERE { 
?search dbpedia Philip_Rivers .
} 
LIMIT 100
```

**Comment by Planeshifter** [comment]
When writing this library, I didn't have this use case in mind. However, it is supported by manually adding the triple in question using the `.registerTriple` method. Try something along these lines:

``` javascript
var myquery = new sparqls.Query();

var triple = {
    'subject': 'dbpedia:Philip_Rivers',
    'predicate': 'dbp:currentteam',
    'object': '?currentteam'
};

myquery
    .registerTriple( triple )
    .selection( 'currentteam' );

console.log(myquery.sparqlQuery);
```

**Comment by tielur** [comment]
@Planeshifter Awesome! I have a few related questions.

##### Filter language:

How would I go about filtering or only requesting the en language of the current team. I noticed a `language` key being specified [here](https://github.com/Planeshifter/node-sparqling-star/blob/master/examples/word_field.js#L22) but that doesn't seem to work for `registerTriple`?

I tried something like:

``` js
var triple = {
    'subject': 'dbpedia:Philip_Rivers',
    'predicate': 'dbp:currentteam',
    'object': '?currentteam',
    'language': 'en'
};
```

or

``` js
var triple = {
    'subject': 'dbpedia:Philip_Rivers@en',
    'predicate': 'dbp:currentteam',
    'object': '?currentteam'
};
```

It seems like I can apply a filter but I'm not sure if that's a good way to do that, ex:

``` js
myquery.filter('LANG(?currentteam) = "" || LANGMATCHES(LANG(?currentteam), "en")')
```

##### More Properties:

If I wanted to expand this query to add additional properties. Would I just add additional triples?
(This works, but I'm not sure if there is a better way)

``` js
var myquery = new sparqls.Query();

var currentTeamTriple = {
    'subject': 'dbpedia:Philip_Rivers',
    'predicate': 'dbp:currentteam',
    'object': '?currentteam'
};

var birthdateTriple = {
  'subject': 'dbpedia:Philip_Rivers',
  'predicate': 'dbo:birthDate',
  'object': '?birthDate'
}


myquery
    .registerTriple( currentTeamTriple )
    .registerTriple( birthdateTriple )
    .selection( ['currentteam', 'birthDate'] );

console.log(myquery.sparqlQuery);
```

**Comment by Planeshifter** [comment]
Yeah, both of your approaches are how I would handle these queries, too. The `registerTripe` function does not offer any functionality to make writing queries easier, it was added precisely to handle the case where you want to add a specific triple that the rest of the API does not handle. I am wondering how one could make the workflow simpler. Let me know if you have any suggestions.

**Comment by tielur** [comment]
If it helps, I'm starting with a very specific resource url: http://dbpedia.org/resource/Philip_Rivers

And I basically want to go get that resource and get specific properties from it and also child resource properties.
